name: Build and Upload BOM a ver.xml

on:
  schedule:
    - cron: '*/10 * * * *'  # Se ejecuta cada 10 minutos
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Check if the file is downloadable
      run: |
        if wget --spider https://github.com/davidmuma/EPG_dobleM/raw/master/guiatv_color.xml.gz 2>/dev/null; then
          echo "File is downloadable."
        else
          echo "File is not downloadable. Exiting job."
          exit 1
        fi

    - name: Download and process EPG data
      run: |
        wget -O guiatv_color.xml.gz https://github.com/davidmuma/EPG_dobleM/raw/master/guiatv_color.xml.gz
        gunzip guiatv_color.xml.gz
        head -n 2 guiatv_color.xml > BOM.xml
        sed -n '/<channel id="BOM Cine">/,/<\/channel>/p' guiatv_color.xml >> BOM.xml
        sed -n '/<programme start=.*channel="BOM Cine">/,/<\/programme>/p' guiatv_color.xml >> BOM.xml
        tail -n 1 guiatv_color.xml >> BOM.xml
        sed -i 's/+0000/+0200/g' BOM.xml

    - name: Remove old BOM.xml if it exists
      run: |
        rm -f BOM.xml

    - name: Move new BOM.xml to repository root
      run: |
        mv BOM.xml /path/to/your/repository

    - name: Commit and push changes
      run: |
        cd /path/to/your/repository
        git add BOM.xml
        git commit -m "Update BOM.xml"
        git push origin main
