name: Resolve Final IPs

on:
  push: # Permite ejecuci칩n manual al hacer push
    branches:
      - main
  workflow_dispatch: # Permite ejecuci칩n manual desde la interfaz de GitHub Actions
  schedule: # Ejecuta autom치ticamente cada hora
    - cron: "10 * * * * "

jobs:
  resolve-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Resolve IP for URLs
        run: |
          urls=("https://tinyurl.com/2v6pcwwd" "https://tinyurl.com/5hbek84b" "https://www.vavoo.tv/api/box/ping2" "https://www2.vavoo.to/live2/index?countries=all&output=json" "https://vavoo.to/live2/play/3923153097.ts" "https://vavoo.to/live2/play/1397846137.ts")
          output="IPs.txt"

          # Crear o sobrescribir el archivo de salida
          echo "Resoluci칩n de IPs:" > $output
          echo "Fecha y hora: $(date)" >> $output
          echo "" >> $output

          for url in "${urls[@]}"; do
            final_url=$(curl -Ls -o /dev/null -w "%{url_effective}" "$url")
            final_ip=$(dig +short $(echo $final_url | awk -F/ '{print $3}'))
            echo "$url : $final_ip" >> $output
          done

          echo "IPs resueltas guardadas en $output"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add IPs.txt
          git commit -m "Update resolved IPs [$(date)]"
          git push



